import React from "react";

const Plus = ({ width = 32, height = 32, color = "#2A2D34" }) => {
  return (
    <svg
      width={width}
      height={height}
      viewBox="0 0 68.51 70.58"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <g id="Layer_2" data-name="Layer 2">
        <g
          id="shopping_and_e-commerceicons"
          data-name="shopping and e-commerceicons"
        >
          <rect
            x="1.03"
            y="21.37"
            width="52.99"
            height="8.97"
            rx="1.87"
            fill="none"
            stroke={color}
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2.06"
          />
          <line
            x1="24.68"
            y1="3.1"
            x2="14.62"
            y2="25.85"
            fill="none"
            stroke={color}
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="6.19"
          />
          <line
            x1="40.8"
            y1="25.85"
            x2="30.74"
            y2="3.1"
            fill="none"
            stroke={color}
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="6.19"
          />
          <path
            d="M43.57,55.3H11.48a2.23,2.23,0,0,1-2.2-1.87L5.34,30.33H49.71l-3.93,23.1A2.24,2.24,0,0,1,43.57,55.3Z"
            fill="none"
            stroke={color}
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2.06"
          />
          <line
            x1="38.2"
            y1="35.33"
            x2="36.92"
            y2="50.3"
            fill="none"
            stroke={color}
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2.06"
          />
          <line
            x1="27.53"
            y1="35.33"
            x2="27.53"
            y2="50.3"
            fill="none"
            stroke={color}
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2.06"
          />
          <line
            x1="16.86"
            y1="35.33"
            x2="18.14"
            y2="50.3"
            fill="none"
            stroke={color}
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2.06"
          />
          <line
            x1="24.68"
            y1="2.3"
            x2="14.62"
            y2="25.85"
            fill="none"
            stroke={color}
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="1.75"
          />
          <line
            x1="40.8"
            y1="25.85"
            x2="30.74"
            y2="2.3"
            fill="none"
            stroke={color}
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="1.75"
          />
          <line
            x1="12.75"
            y1="25.85"
            x2="16.49"
            y2="25.85"
            fill="none"
            stroke={color}
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2.06"
          />
          <line
            x1="38.93"
            y1="25.85"
            x2="42.67"
            y2="25.85"
            fill="none"
            stroke={color}
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2.06"
          />
          <line
            x1="47.12"
            y1="55.3"
            x2="59.35"
            y2="55.3"
            fill="none"
            stroke={color}
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2.06"
          />
          <line
            x1="53.23"
            y1="61.41"
            x2="53.23"
            y2="49.18"
            fill="none"
            stroke={color}
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2.06"
          />
          <circle
            cx="53.23"
            cy="55.3"
            r="12.19"
            transform="translate(-12.82 94.4) rotate(-76.72)"
            fill="none"
            stroke={color}
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2.06"
          />
        </g>
      </g>
    </svg>
  );
};

// SVG plus icon
export default React.memo(Plus);
